name = "qk_service_template"
compatibility_date = "2024-08-22"

routes = [
    { pattern = "api.questkeeper.app/v1/notifications*", zone_name = "questkeeper.app" },
]

[vars]
SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co"
FCM_PROJECT_ID = "479691835174"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-wh0yl@assigngo-d890c.iam.gserviceaccount.com"
FIREBASE_PROJECT_ID = "assigngo-d890c"

[placement]
mode = "off"

[env.dev]
vars = { ENVIRONMENT = "dev", SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co" }