name = "qk_service_template"
compatibility_date = "2024-08-22"

routes = [
    { pattern = "api.questkeeper.app/v1/template*", zone_name = "questkeeper.app" },
]

[vars]
SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co"

[placement]
mode = "off"

[env.dev]
vars = { ENVIRONMENT = "dev", SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co" }